ig:
  name: big
  myPojoList:
    - name: my name1
      description: my description1
    - name: my name2
      description: my description2
---
spring:
  profiles: dev
ig:
  name: big-dev
  myPojoList:
    - name: my name1 dev
      description: my description1 dev
---
spring:
  profiles: prod
ig:
  name: big-prod
  myPojoList:
    - name: my name1 prod
      description: my description1 prod
    - name: my name2 prod
      description: my description2 prod
    - name: my name3 prod
      description: my description3 prod